services:
  db:
    image: postgres:13.21-alpine3.22
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myPOSTGRES_USER
      - POSTGRES_PASSWORD=myPOSTGRES_PASSWORD
      - POSTGRES_DB=myPOSTGRES_DB
    networks:
      - network.api.config.docker.file
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: .
    container_name: api
    ports:
      - 3000:3000
    networks:
      - network.api.config.docker.file
    depends_on:
      - db

networks:
  network.api.config.docker.file:
    name: network.api.config.docker.file
    driver: bridge

volumes:
  db:
